### ISSUE TITLE
'assimp/anim.h' file not found

### ISSUE THREAD

**Issue by nathany** [krux02/turnt-octo-wallhack#2]
I get this error when trying to build on OS X 10.9.4:

```
# github.com/krux02/assimp
../assimp/Anim.go:4:10: fatal error: 'assimp/anim.h' file not found
#include <assimp/anim.h>
         ^
1 error generated.
```

**Comment by krux02** [comment]
Seems like I did not add a readme very soon. And the readme I do not know if it helps, but it's better than nothing. Since I am not working on this project anymore, I close this issue now. But I would still accept pull request when they are necessary to make this project compileable, but I will not do any active work to keep this code alive.
